### ISSUE TITLE
Update code samples to 2014 best practises

### ISSUE THREAD

**Issue by mikaelhg** [oreillymedia/java_cookbook_3e#1]
If you are going to publish a new edition of the book, please make sure to update any example code to the best practises recommended to practising developers at 2014.

A brief browse through the repository produced numerous examples of code one would not wish junior developers to emulate in commercial development.

Please at least run PMD and FindBugs against the code.

**Comment by karent** [comment]
I'm sorry to hear you found problems in the example code for this title. I've contacted the editor of the book to see if we are able to get updated examples to post to this repo.

**Comment by karent** [comment]
The editor is wondering if perhaps you could provide more specifics. "The best practises recommended" is too vague for us to pinpoint areas of the code that need improvement. 

If you could please provide some examples of code examples that need to be updated, we will look into the best way to make those changes.

**Comment by mikaelhg** [comment]
Examples were updated.
